### ISSUE TITLE
i2c bottleneck causing issues

### ISSUE THREAD

**Issue by HomerSp** [Dygmalab/Raise-Firmware#10]
So I've been looking at why the latency of the keyboard is so large when using the rainbow LED modes.
I've written some code to lower and raise the speed of the animation to try and figure out what's going on, and I can say that on higher speeds the latency is very high (I don't have tools to measure this, but it's very noticeable when typing). At first I thought the CPU just wasn't up to doing all of the calculations required to have a nice effect, so I rewrote parts of it to make the calculation faster, but the latency wasn't really any better.
Then I tried removing the call that sends the data to i2c, and the latency was immediately better (of course without any LEDs actually showing, but the calculations were still there). This led me to the I2C clock speed, which I tried increasing and it was immediately much better.
I can see it was lowered to 100khz here: https://github.com/Dygmalab/Kaleidoscope/commit/14cb9aa90870352041b466cd2cbbebed95e86a73 But I've been running it at 400khz for hours now with no issues and according to the specs it should be able to run at that speed, so I'm wondering if the firmware is more stable now to allow it to run at that higher speed.

I'll do some more testing, and if it turns out this is stable, I feel like it probably should be increased to remove the bottleneck.

**Comment by AlexDygma** [comment]
Yea I'm pushing this fix to the next update to 200Khz, if it works OK we will push it again to 400Khz so that we confirm it's all stable, as i don't know yet why they downgraded the speed before.

**Comment by AlexDygma** [comment]
Btw @HomerSp speaking with @mattvenn about this, he remembered me that this was tuned down to better get through immunity testing, as it seems to make the raise more prone to EM and ESD problems, which we are trying to mitigate now.

As now the keyboard no longer freezes, it just restarts, this should be testable and shouldn't hurt much the users in general.

we are going to center in solving the i2c channel issues for good for this month, I'm making changes to the SERCOM library, first updating it to it's most recent version which has newer implementations of a better handler, those modifications can be found in the branch #13 

hope to hear from you soon! 👍 
Best regards, Alex.

**Comment by HomerSp** [comment]
Interesting, that does make sense. Luckily I haven't had any freezes at all - and I've been running mine at 400khz since I did this PR (but I didnt have any before this either).

Have you found a good way to reproduce the ESD issue?

**Comment by AlexDygma** [comment]
This should work https://www.amazon.com/shock-pen/s?k=shock+pen 😆

**Comment by AlexDygma** [comment]
This has been raised to 200Khz for the latest firmware and seems to work correctly will see the evolution of it now that the freezing is fixed :)
