### ISSUE TITLE
Failed to clone source code

### ISSUE THREAD

**Issue by nosleduc** [Dygmalab/Raise-Firmware#21]
The following command line failed at
git clone --recursive https://github.com/Dygmalab/Kaleidoscope-Bundle-Dygma.git hardware/dygma/samd

Fetched in submodule path 'libraries/Kaleidoscope', but it did not contain 67176f4f3730790580e0068675498d3245eaf57b. Direct fetching of that commit failed.

**Comment by AlexDygma** [comment]
Hey! this should be solved, can you try again?

**Comment by nosleduc** [comment]
It works

**Comment by AlexDygma** [comment]
Fixed!
